# Generated by Django 3.1.7 on 2021-03-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buatrencana',
            options={'ordering': ('tgl_eksekusi',), 'verbose_name': 'Rencana', 'verbose_name_plural': 'Daftar Rencana'},
        ),
    ]
