# Generated by Django 3.2.6 on 2021-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='token_auth',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token'),
        ),
    ]
