# Generated by Django 3.2.6 on 2021-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extenduser_tgl_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='tgl_token',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
