# Generated by Django 3.2.6 on 2021-09-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_extenduser_tgl_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
