# Generated by Django 3.1.7 on 2021-03-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210330_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bidang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bidang'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_kabid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
