# Generated by Django 3.1.7 on 2021-03-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210330_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='bidang',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Bidang',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
