# Generated by Django 3.1.7 on 2021-03-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bidang_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bidang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bidang'),
        ),
    ]
