# Generated by Django 3.1.7 on 2021-03-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210331_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('nama',), 'verbose_name': 'Profile User', 'verbose_name_plural': 'Daftar Profile User'},
        ),
    ]
