# Generated by Django 3.2.6 on 2021-08-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisUraian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uraian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_uraian', models.CharField(max_length=100)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.jenisuraian')),
            ],
        ),
        migrations.CreateModel(
            name='TargetRealisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_tahun', models.CharField(blank=True, max_length=50, null=True)),
                ('target_bln_lapor', models.CharField(blank=True, max_length=50, null=True)),
                ('realisasi_sd_bln_lalu', models.CharField(blank=True, max_length=50, null=True)),
                ('realisasi_bln_lapor', models.CharField(blank=True, max_length=50, null=True)),
                ('realiasi_sd_bln_lapor', models.CharField(blank=True, max_length=50, null=True)),
                ('periode', models.DateField()),
                ('tgl_upload', models.DateTimeField(auto_now_add=True)),
                ('uraian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.uraian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
