# Generated by Django 3.2.6 on 2021-08-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uraian',
            name='jenis',
        ),
        migrations.AddField(
            model_name='targetrealisasi',
            name='jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.jenisuraian'),
            preserve_default=False,
        ),
    ]
