# Generated by Django 3.2.6 on 2021-08-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0002_auto_20210808_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetrealisasi',
            old_name='realiasi_sd_bln_lapor',
            new_name='realisasi_sd_bln_lapor',
        ),
    ]
